### ISSUE TITLE
通信协议

### ISSUE THREAD

**Issue by crueluncle** [TargetLiu/golang-chat#1]
看你代码发送、接收消息直接是con.write() ,con.read(),如何解决tcp粘包问题的？

**Comment by TargetLiu** [comment]
这个只是我学习Go语言的一个示例代码哈，简单的学习下TCP链接。粘包的问题的确会存在，如果要解决粘包问题可以参考下[这个文章](http://www.01happy.com/golang-tcp-socket-adhere/)

**Comment by TargetLiu** [comment]
> 看你代码发送、接收消息直接是con.write() ,con.read(),如何解决tcp粘包问题的？

@crueluncle 最近闲来无事更新了一下，加了一个协议来解决粘包问题
